// @app/layout.tsx

// Description
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// Components
import { ThemeProvider } from "@/components/provider/themeProvider";

// Hooks
import ClientOnly from "@/components/hydration/mounted";

// CSS
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientOnly>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            storageKey="color-theme"
            themes={["light", "dark"]}
            enableSystem={true}
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </ClientOnly>
      </body>
    </html>
  );
}
